# Generated by Django 4.1.7 on 2023-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=15)),
                ('comfirmpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
