# Generated by Django 4.1.7 on 2023-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_credential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
